[http.routers]
  [http.routers.backend]
    rule = "Host(`api.dashboard.zara`) || Host(`www.api.dashboard.zara`)"
    middlewares = ["no-www"]
    service = "backend"
  [http.routers.frontend]
    rule = "Host(`dashboard.zara`) || Host(`www.dashboard.zara`)"
    middlewares = ["no-www"]
    service = "frontend"
  [http.routers.traefik]
    rule = "Host(`traefik.localhost`)"
    service = "api@internal"

[http.services]
  [http.services.backend.loadBalancer]
    [[http.services.backend.loadBalancer.servers]]
      url = "http://127.0.0.1:3000/"
  [http.services.frontend.loadBalancer]
    [[http.services.frontend.loadBalancer.servers]]
      url = "http://127.0.0.1:8080/"

[http.middlewares]
  [http.middlewares.no-www.redirectRegex]
    regex = '^http:\/\/www\.(.*)'
    replacement = "http://${1}"